In [1]:
import diopy
import pandas as pd
import scanpy as sc 
import scanpy.external as sce
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
sc.settings.verbosity = 3             # verbosity: errors (0), warnings (1), info (2), hints (3)
sc.logging.print_header()

/bigdata/zlin/miniconda3/envs/scrna/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2023-05-17 13:58:30.451360: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-17 13:58:30.575380: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-05-17 13:58:31.211142: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-05-17 13:58:31.211232: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-05-17 13:58:31.211238: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.

scanpy==1.9.3 anndata==0.9.1 umap==0.5.3 numpy==1.21.6 scipy==1.9.1 pandas==1.5.3 scikit-learn==1.2.2 statsmodels==0.13.5 python-igraph==0.10.4 louvain==0.8.0 pynndescent==0.5.10

In [3]:
becker = diopy.input.read_h5(file='/bigdata/zlin/Melanoma_meta/data/Myeloids/becker.h5')
franken = diopy.input.read_h5(file='/bigdata/zlin/Melanoma_meta/data/Myeloids/franken.h5')
bassez1 = diopy.input.read_h5(file='/bigdata/zlin/Melanoma_meta/data/Myeloids/bassez1.h5')
bassez2 = diopy.input.read_h5(file='/bigdata/zlin/Melanoma_meta/data/Myeloids/bassez2.h5')
yost = diopy.input.read_h5(file='/bigdata/zlin/Melanoma_meta/data/Myeloids/yost.h5')
crc_li = diopy.input.read_h5(file='/bigdata/zlin/Melanoma_meta/data/Myeloids/crc_li.h5')
tnbc_li = diopy.input.read_h5(file='/bigdata/zlin/Melanoma_meta/data/Myeloids/tnbc_li.h5')

In [14]:
print(pd.crosstab(becker.obs['sample'],becker.obs['time_point']))
print(pd.crosstab(franken.obs['sample'],franken.obs['time_point']))
print(pd.crosstab(bassez1.obs['sample'],bassez1.obs['time_point']))
print(pd.crosstab(bassez2.obs['sample'],bassez2.obs['time_point']))
print(pd.crosstab(yost.obs['sample'],yost.obs['time_point']))
print(pd.crosstab(crc_li.obs['sample'],crc_li.obs['time_point']))
print(pd.crosstab(tnbc_li.obs['sample'],tnbc_li.obs['time_point']))

time_point  Before   On
sample
P1_Before      305    0
P1_On            0  179
P10_Before      34    0
P11_Before     401    0
P11_On           0   66
P12_Before     151    0
P12_On           0  296
P2_Before       18    0
P2_On            0   74
P3_Before      254    0
P3_On            0  356
P4_Before       31    0
P5_Before       12    0
P5_On            0  188
P6_Before      141    0
P6_On            0    7
P7_Before       94    0
P7_On            0  146
P8_Before        8    0
P9_Before       94    0
P9_On            0  166
time_point     On   Pre
sample
1_On         1946     0
1_Pre           0  1086
10_On         809     0
10_Pre          0   398
11_On          64     0
11_Pre          0   922
12_On        2475     0
12_Pre          0  3006
13_On        1172     0
13_Pre          0  1170
14_On         572     0
14_Pre          0  1798
15_On         937     0
15_Pre          0  1758
16_On         237     0
17_On         814     0
17_Pre          0   666
18_On         588     0
18_Pre          0   962
19_On         180     0
19_Pre          0   442
2_On          192     0
2_Pre           0  1111
20_Pre          0   502
3_On          429     0
3_Pre           0   426
4_On        33187     0
4_Pre           0  3744
5_On          607     0
5_Pre           0  2155
6_On          854     0
6_Pre           0  5538
7_On          571     0
7_Pre           0   684
8_On          389     0
8_Pre           0  2887
9_On         1472     0
9_Pre           0   594
time_point     Pre    On
sample
BIOKEY_10_On     0   746
BIOKEY_10_Pre  224     0
BIOKEY_11_On     0   407
BIOKEY_11_Pre  207     0
BIOKEY_12_On     0   433
BIOKEY_12_Pre  315     0
BIOKEY_14_On     0    44
BIOKEY_14_Pre  189     0
BIOKEY_15_On     0   453
BIOKEY_15_Pre  402     0
BIOKEY_16_On     0  1591
BIOKEY_16_Pre  772     0
BIOKEY_17_On     0   267
BIOKEY_17_Pre  103     0
BIOKEY_18_On     0   267
BIOKEY_18_Pre  144     0
BIOKEY_19_On     0   295
BIOKEY_19_Pre  222     0
BIOKEY_2_On      0   333
BIOKEY_2_Pre   445     0
BIOKEY_20_On     0   392
BIOKEY_20_Pre   22     0
BIOKEY_21_On     0   173
BIOKEY_21_Pre  179     0
BIOKEY_22_On     0    62
BIOKEY_22_Pre   30     0
BIOKEY_23_On     0   839
BIOKEY_24_On     0   269
BIOKEY_24_Pre  234     0
BIOKEY_25_On     0    27
BIOKEY_25_Pre   32     0
BIOKEY_26_On     0   164
BIOKEY_26_Pre  115     0
BIOKEY_27_On     0   108
BIOKEY_27_Pre  148     0
BIOKEY_28_On     0  1092
BIOKEY_28_Pre  170     0
BIOKEY_29_On     0    27
BIOKEY_29_Pre  124     0
BIOKEY_3_On      0   242
BIOKEY_3_Pre   357     0
BIOKEY_30_On     0   228
BIOKEY_30_Pre  110     0
BIOKEY_31_On     0   600
BIOKEY_31_Pre  383     0
BIOKEY_4_On      0   250
BIOKEY_4_Pre   286     0
BIOKEY_5_On      0   110
BIOKEY_5_Pre   286     0
BIOKEY_6_On      0   295
BIOKEY_6_Pre   404     0
BIOKEY_7_On      0   344
BIOKEY_7_Pre    52     0
BIOKEY_8_On      0   366
BIOKEY_8_Pre   107     0
BIOKEY_9_On      0    93
BIOKEY_9_Pre   168     0
time_point      Pre    On
sample
BIOKEY_32_On      0    67
BIOKEY_32_Pre    23     0
BIOKEY_33_On      0   358
BIOKEY_33_Pre    72     0
BIOKEY_34_On      0  1287
BIOKEY_34_Pre   103     0
BIOKEY_35_On      0  1295
BIOKEY_35_Pre  1254     0
BIOKEY_36_On      0   505
BIOKEY_36_Pre     4     0
BIOKEY_37_On      0   257
BIOKEY_37_Pre   252     0
BIOKEY_38_On      0    61
BIOKEY_38_Pre    11     0
BIOKEY_39_On      0   266
BIOKEY_39_Pre     8     0
BIOKEY_40_On      0   267
BIOKEY_40_Pre    74     0
BIOKEY_41_On      0   130
BIOKEY_41_Pre   262     0
BIOKEY_42_On      0   146
BIOKEY_42_Pre    39     0
time_point  Post  Pre
sample
su001_Post   399    0
su001_Pre      0   74
su003_Post    57    0
su003_Pre      0   34
su004_Post   298    0
su004_Pre      0   34
su005_Post   996    0
su005_Pre      0  926
su006_Post   592    0
su006_Pre      0  167
su007_Pre      0   65
su008_Post   602    0
su008_Pre      0  228
su009_Post     3    0
su012_Post     2    0
su012_Pre      0    1
time_point  Post  Pre
sample
P21_Post     128    0
P21_Pre        0   66
P24_Post     137    0
P24_Pre        0   76
P25_Post      84    0
P25_Pre        0  515
P27_Post     124    0
P27_Pre        0  309
P28_Post       2    0
P28_Pre        0  255
P30_Post      15    0
P30_Pre        0   70
P31_Post      34    0
P31_Pre        0   42
time_point  Post   Pre
sample
Post_P002     56     0
Post_P005    431     0
Post_P012     94     0
Post_P013   2313     0
Post_P017    663     0
Post_P018    334     0
Post_P019    122     0
Post_P022    209     0
Post_P023    156     0
Post_P025    114     0
Pre_P002       0   165
Pre_P005       0   122
Pre_P012       0   210
Pre_P013       0  2295
Pre_P017       0   858
Pre_P018       0   361
Pre_P019       0   505
Pre_P022       0   447
Pre_P023       0   258
Pre_P025       0   215

In [15]:
datasets = [becker, yost, bassez1, bassez2, franken, crc_li, tnbc_li]

In [16]:
def rm_patients(adata):
    ct = pd.crosstab(adata.obs['patient'], adata.obs['time_point'])
    rm = ct[(ct.iloc[:, 0] < 50) | (ct.iloc[:, 1] < 50)]
    return rm.index.tolist()

In [20]:
# remove samples with insufficient cell numbers
rm_becker = rm_patients(becker)
rm_franken = rm_patients(franken)
rm_bassez1 = rm_patients(bassez1)
rm_bassez2 = rm_patients(bassez2)
rm_yost = rm_patients(yost)
rm_crc_li = rm_patients(crc_li)
rm_tnbc_li = rm_patients(tnbc_li)
print(rm_becker, rm_franken, rm_bassez1, rm_bassez2, rm_yost, rm_crc_li, rm_tnbc_li)

['P10', 'P2', 'P4', 'P5', 'P6', 'P8'] [16, 20] ['BIOKEY_14', 'BIOKEY_20', 'BIOKEY_22', 'BIOKEY_23', 'BIOKEY_25', 'BIOKEY_29'] ['BIOKEY_32', 'BIOKEY_36', 'BIOKEY_38', 'BIOKEY_39', 'BIOKEY_42'] ['su003', 'su004', 'su007', 'su009', 'su012'] ['P28', 'P30', 'P31'] []

In [21]:
becker = becker[~becker.obs['patient'].isin(rm_becker)]
franken = franken[~franken.obs['patient'].isin(rm_franken)]
bassez1 = bassez1[~bassez1.obs['patient'].isin(rm_bassez1)]
bassez2 = bassez2[~bassez2.obs['patient'].isin(rm_bassez2)]
yost = yost[~yost.obs['patient'].isin(rm_yost)]
crc_li = crc_li[~crc_li.obs['patient'].isin(rm_crc_li)]
tnbc_li = tnbc_li[~tnbc_li.obs['patient'].isin(rm_tnbc_li)]

In [22]:
dataset_list = [becker, yost,bassez1, bassez2, franken, crc_li, tnbc_li]

In [23]:
dataset_list[0] = dataset_list[0][~dataset_list[0].obs['celltype_sc_r2'].isin(['Mast_KIT'])]
for i in range(len(dataset_list)):
    dataset_list[i].obs['celltype_subtype'] = dataset_list[i].obs['celltype_sc_r2'].astype(str)
    dataset_list[i].obs.loc[dataset_list[i].obs['celltype_subtype'].str.contains('cDC2'),'celltype_subtype'] = 'cDC2'

/tmp/ipykernel_3194558/2793487121.py:3: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  dataset_list[i].obs['celltype_subtype'] = dataset_list[i].obs['celltype_sc_r2'].astype(str)
/tmp/ipykernel_3194558/2793487121.py:3: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  dataset_list[i].obs['celltype_subtype'] = dataset_list[i].obs['celltype_sc_r2'].astype(str)

In [42]:
pd.crosstab(becker.obs['celltype_sc_r2'],becker.obs['sample'])

sample,P1_Before,P1_On,P11_Before,P11_On,P12_Before,P12_On,P3_Before,P3_On,P7_Before,P7_On,P9_Before,P9_On
celltype_sc_r2,,,,,,,,,,,,
cDC1_CLEC9A,0,3,3,1,2,1,27,21,2,1,1,1
cDC2_CD1A,6,0,13,3,7,12,30,11,5,5,3,3
cDC2_CXCL9,13,7,15,0,2,15,10,33,3,3,3,11
cDC2_CXCR4hi,2,0,2,0,0,2,3,1,1,0,0,0
cDC2_FCN1,8,1,2,0,0,5,3,0,1,1,0,2
cDC2_IL1B,0,0,0,0,0,0,3,0,0,0,0,0
cDC2_ISG15,0,0,2,0,0,0,0,1,0,0,0,1
cDC3_LAMP3,6,6,5,0,0,4,42,22,1,0,0,0
Macro_C1QC,38,8,82,21,62,49,23,56,19,46,36,23
Macro_FN1,0,0,3,0,1,1,0,0,0,1,1,2
Macro_GPNMB,73,12,74,11,24,66,18,46,15,17,9,38
Macro_IL1B,1,3,5,0,3,2,0,0,2,0,2,2
Macro_INHBA,1,1,1,0,0,0,0,0,1,0,0,0
Macro_ISG15,93,100,58,10,19,73,5,87,14,3,7,35
Macro_LYVE1,1,2,20,1,4,5,3,2,4,22,2,0
Macro_NLRP3,5,12,17,1,4,5,7,4,7,4,2,2
Macro_SPP1,14,5,33,7,12,18,1,5,10,27,19,10
Mast_KIT,0,0,0,0,0,0,0,1,0,0,0,0
Mono_CD14,0,1,1,0,1,0,2,1,0,1,0,0
Mono_CD14CD16,10,3,43,10,9,14,15,29,7,12,5,21
Mono_CD16,1,0,2,1,1,1,2,4,2,3,1,0
pDC_LILRA4,33,15,20,0,0,23,60,32,0,0,3,15

In [52]:
becker.obs['celltype_count'] = becker.obs.groupby(['sample','celltype_sc_r2'])['celltype_sc_r2'].transform('count')
becker.obs['sample_total'] = becker.obs.groupby(['sample'])['celltype_sc_r2'].transform('count')
becker.obs['celltype_proportion'] = becker.obs['celltype_count'] / becker.obs['sample_total']

In [ ]:
becker.obs['celltype_count'] = becker.obs.groupby(['sample','celltype_sc_r2'])['celltype_sc_r2'].transform('count')
becker.obs['sample_total'] = becker.obs.groupby(['sample'])['celltype_sc_r2'].transform('count')
becker.obs['celltype_proportion'] = becker.obs['celltype_count'] / becker.obs['sample_total']

In [82]:
# Step 2: pivot dataframe to have celltypes as columns with their proportions as values
pivot_df = becker.obs.pivot_table(values='celltype_proportion', index=['patient', 'time_point','response','treatment'], columns='celltype_sc_r2')
pivot_df.fillna(0.001, inplace=True)
pivot_df

# pivot_df.reset_index(inplace=True)

# pre_df = pivot_df[pivot_df['time_point'] == 'Before'].set_index('patient')

# on_df = pivot_df[pivot_df['time_point'] == 'On'].set_index('patient')
# proportion_columns = [col for col in pivot_df.columns if col not in ['patient', 'time_point','response','treatment']]
# fold_change_df = on_df[proportion_columns].divide(pre_df[proportion_columns]).reset_index()
# fold_change_df

celltype_sc_r2                         cDC1_CLEC9A  cDC2_CD1A  cDC2_CXCL9  \
patient time_point response treatment
P1      Before     PR       PD1+CTLA4     0.001000   0.019672    0.042623
        On         PR       PD1+CTLA4     0.016760   0.001000    0.039106
P11     Before     SD       PD1           0.007481   0.032419    0.037406
        On         SD       PD1           0.015152   0.045455    0.001000
P12     Before     PD       PD1           0.013245   0.046358    0.013245
        On         PD       PD1           0.003378   0.040541    0.050676
P3      Before     SD       PD1+CTLA4     0.106299   0.118110    0.039370
        On         SD       PD1+CTLA4     0.058989   0.030899    0.092697
P7      Before     NE       PD1           0.021277   0.053191    0.031915
        On         NE       PD1           0.006849   0.034247    0.020548
P9      Before     PD       PD1           0.010638   0.031915    0.031915
        On         PD       PD1           0.006024   0.018072    0.066265

celltype_sc_r2                         cDC2_CXCR4hi  cDC2_FCN1  cDC2_IL1B  \
patient time_point response treatment
P1      Before     PR       PD1+CTLA4      0.006557   0.026230   0.001000
        On         PR       PD1+CTLA4      0.001000   0.005587   0.001000
P11     Before     SD       PD1            0.004988   0.004988   0.001000
        On         SD       PD1            0.001000   0.001000   0.001000
P12     Before     PD       PD1            0.001000   0.001000   0.001000
        On         PD       PD1            0.006757   0.016892   0.001000
P3      Before     SD       PD1+CTLA4      0.011811   0.011811   0.011811
        On         SD       PD1+CTLA4      0.002809   0.001000   0.001000
P7      Before     NE       PD1            0.010638   0.010638   0.001000
        On         NE       PD1            0.001000   0.006849   0.001000
P9      Before     PD       PD1            0.001000   0.001000   0.001000
        On         PD       PD1            0.001000   0.012048   0.001000

celltype_sc_r2                         cDC2_ISG15  cDC3_LAMP3  Macro_C1QC  \
patient time_point response treatment
P1      Before     PR       PD1+CTLA4    0.001000    0.019672    0.124590
        On         PR       PD1+CTLA4    0.001000    0.033520    0.044693
P11     Before     SD       PD1          0.004988    0.012469    0.204489
        On         SD       PD1          0.001000    0.001000    0.318182
P12     Before     PD       PD1          0.001000    0.001000    0.410596
        On         PD       PD1          0.001000    0.013514    0.165541
P3      Before     SD       PD1+CTLA4    0.001000    0.165354    0.090551
        On         SD       PD1+CTLA4    0.002809    0.061798    0.157303
P7      Before     NE       PD1          0.001000    0.010638    0.202128
        On         NE       PD1          0.001000    0.001000    0.315068
P9      Before     PD       PD1          0.001000    0.001000    0.382979
        On         PD       PD1          0.006024    0.001000    0.138554

celltype_sc_r2                         Macro_FN1  ...  Macro_INHBA  \
patient time_point response treatment             ...
P1      Before     PR       PD1+CTLA4   0.001000  ...     0.003279
        On         PR       PD1+CTLA4   0.001000  ...     0.005587
P11     Before     SD       PD1         0.007481  ...     0.002494
        On         SD       PD1         0.001000  ...     0.001000
P12     Before     PD       PD1         0.006623  ...     0.001000
        On         PD       PD1         0.003378  ...     0.001000
P3      Before     SD       PD1+CTLA4   0.001000  ...     0.001000
        On         SD       PD1+CTLA4   0.001000  ...     0.001000
P7      Before     NE       PD1         0.001000  ...     0.010638
        On         NE       PD1         0.006849  ...     0.001000
P9      Before     PD       PD1         0.010638  ...     0.001000
        On         PD       PD1         0.012048  ...     0.001000

celltype_sc_r2                         Macro_ISG15  Macro_LYVE1  Macro_NLRP3  \
patient time_point response treatment
P1      Before     PR       PD1+CTLA4     0.304918     0.003279     0.016393
        On         PR       PD1+CTLA4     0.558659     0.011173     0.067039
P11     Before     SD       PD1           0.144638     0.049875     0.042394
        On         SD       PD1           0.151515     0.015152     0.015152
P12     Before     PD       PD1           0.125828     0.026490     0.026490
        On         PD       PD1           0.246622     0.016892     0.016892
P3      Before     SD       PD1+CTLA4     0.019685     0.011811     0.027559
        On         SD       PD1+CTLA4     0.244382     0.005618     0.011236
P7      Before     NE       PD1           0.148936     0.042553     0.074468
        On         NE       PD1           0.020548     0.150685     0.027397
P9      Before     PD       PD1           0.074468     0.021277     0.021277
        On         PD       PD1           0.210843     0.001000     0.012048

celltype_sc_r2                         Macro_SPP1  Mast_KIT  Mono_CD14  \
patient time_point response treatment
P1      Before     PR       PD1+CTLA4    0.045902  0.001000   0.001000
        On         PR       PD1+CTLA4    0.027933  0.001000   0.005587
P11     Before     SD       PD1          0.082294  0.001000   0.002494
        On         SD       PD1          0.106061  0.001000   0.001000
P12     Before     PD       PD1          0.079470  0.001000   0.006623
        On         PD       PD1          0.060811  0.001000   0.001000
P3      Before     SD       PD1+CTLA4    0.003937  0.001000   0.007874
        On         SD       PD1+CTLA4    0.014045  0.002809   0.002809
P7      Before     NE       PD1          0.106383  0.001000   0.001000
        On         NE       PD1          0.184932  0.001000   0.006849
P9      Before     PD       PD1          0.202128  0.001000   0.001000
        On         PD       PD1          0.060241  0.001000   0.001000

celltype_sc_r2                         Mono_CD14CD16  Mono_CD16  pDC_LILRA4
patient time_point response treatment
P1      Before     PR       PD1+CTLA4       0.032787   0.003279    0.108197
        On         PR       PD1+CTLA4       0.016760   0.001000    0.083799
P11     Before     SD       PD1             0.107232   0.004988    0.049875
        On         SD       PD1             0.151515   0.015152    0.001000
P12     Before     PD       PD1             0.059603   0.006623    0.001000
        On         PD       PD1             0.047297   0.003378    0.077703
P3      Before     SD       PD1+CTLA4       0.059055   0.007874    0.236220
        On         SD       PD1+CTLA4       0.081461   0.011236    0.089888
P7      Before     NE       PD1             0.074468   0.021277    0.001000
        On         NE       PD1             0.082192   0.020548    0.001000
P9      Before     PD       PD1             0.053191   0.010638    0.031915
        On         PD       PD1             0.126506   0.001000    0.090361

[12 rows x 22 columns]