In [3]:
import numpy as np
import pandas as pd
import scanpy as sc 
import anndata as ad
import scanpy.external as sce
import matplotlib.pyplot as plt

In [4]:
sc.settings.verbosity = 3             # verbosity: errors (0), warnings (1), info (2), hints (3)
sc.logging.print_header()
sc.settings.set_figure_params(dpi=80, facecolor='white')
# maximum number of columns
pd.options.display.max_columns = None
pd.options.display.max_rows = None

scanpy==1.9.8 anndata==0.10.5.post1 umap==0.5.5 numpy==1.26.4 scipy==1.12.0 pandas==2.2.1 scikit-learn==1.4.1.post1 statsmodels==0.14.1 igraph==0.11.4 pynndescent==0.5.11

In [5]:
adata_cd45p = sc.read_h5ad('/bigdata/zlin/PanCancer_ICI/data/TNBC_Shiao/GSE246613_PembroRT_immune_R100_final.h5ad')
adata_cd45n = sc.read_h5ad('/bigdata/zlin/PanCancer_ICI/data/TNBC_Shiao/GSE246613_PembroRT_non_immune_cells.h5ad')

In [6]:
adata_cd45n.obs.columns

Index(['n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts',
       'log1p_total_counts', 'pct_counts_in_top_50_genes',
       'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes',
       'pct_counts_in_top_500_genes', 'percent_mito', 'n_counts',
       'percent_ribo', 'scrublet', 'batch', 'cohort', 'leiden',
       'predicted_labels', 'over_clustering', 'majority_voting', 'conf_score',
       'old_celltype', 'old_subtype', 'celltype_new', 'treatment',
       'response_group', 'subtype_new'],
      dtype='object')

In [7]:
adata_cd45n.obs=adata_cd45n.obs[['batch','cohort','treatment','response_group']]

In [10]:
adata_cd45n.obs.head()

                          batch     cohort treatment response_group
h01A_P_AAACCTGCAACTTGAC  h01A_P  Patient01      Base             R2
h01A_P_AAACCTGCATTATCTC  h01A_P  Patient01      Base             R2
h01A_P_AAACCTGGTTGTCGCG  h01A_P  Patient01      Base             R2
h01A_P_AAACCTGTCTCTGCTG  h01A_P  Patient01      Base             R2
h01A_P_AAACGGGAGAGGTTAT  h01A_P  Patient01      Base             R2

In [8]:
pd.crosstab(adata_cd45n.obs['cohort'], adata_cd45n.obs['response_group'])

response_group     NR     R1     R2
cohort
Patient01           0      0   2051
Patient02           0    689      0
Patient03T1         0      0     97
Patient03T2         0      0    482
Patient04           0    544      0
Patient05           0   1304      0
Patient06        2059      0      0
Patient07           0    639      0
Patient09           0    695      0
Patient10        2066      0      0
Patient11           0      0   1341
Patient12           0   2879      0
Patient15        1056      0      0
Patient16           0  14825      0
Patient17        6278      0      0
Patient18           0      0   2444
Patient19           0      0   4995
Patient20           0      0    454
Patient23           0      0    834
Patient26        7234      0      0
Patient30           0      0    447
Patient39        4991      0      0
Patient42           0      0   8886
Patient43           0  15093      0
Patient45        5561      0      0
Patient46           0      0   4945
Patient47           0      0   9656
Patient48           0   4440      0
Patient52       15698      0      0
Patient53       20507      0      0
Patient56           0      0  12587
Patient57        3006      0      0
Patient63           0      0  11016
Patient64        1377      0      0
Patient66           0      0    570

In [9]:
adata_cd45p.obs.head()

,n_genes_by_counts,log1p_n_genes_by_counts,total_counts,log1p_total_counts,pct_counts_in_top_50_genes,pct_counts_in_top_100_genes,pct_counts_in_top_200_genes,pct_counts_in_top_500_genes,percent_mito,n_counts,percent_ribo,scrublet,batch,CD45_enrich,batch_num,cohort,pCR,RCB,cleared_nodes,treatment,patient_treatment,hormone_receptor,combined_tcr,umap1,umap2,leiden_50nbr_res1.2,celltype,global_clusters,bcell_leiden_nbr100_res0.6,tcell_leiden_nbr100_res0.6,myeloid_leiden_nbr30_res0.8,subcluster
h01A_P_AAACCTGAGACAGACC,691,6.539586,1354.0,7.211557,37.518464,49.335303,63.737075,85.893648,0.045052,1354.0,0.127770,False,h01A_P,P,0,Patient01,R,0,Y,Base,Patient01_Base,TNBC,nan,12.238769,-7.196668,22,myeloid,12,NaN,NaN,12,myeloid_10
h01A_P_AAACCTGAGATGTGTA,3328,8.110427,15093.0,9.622052,41.065395,49.479891,58.702710,71.556351,0.007354,15093.0,0.061287,False,h01A_P,P,0,Patient01,R,0,Y,Base,Patient01_Base,TNBC,nan,5.326361,-0.320588,22,myeloid,12,NaN,NaN,08,myeloid_05
h01A_P_AAACCTGAGCGCTTAT,1675,7.424165,5568.0,8.624970,37.230603,50.053879,62.679598,77.298851,0.020654,5568.0,0.242996,False,h01A_P,P,0,Patient01,R,0,Y,Base,Patient01_Base,TNBC,nan,14.234969,0.425975,23,myeloid,9,NaN,NaN,04,myeloid_09
h01A_P_AAACCTGAGGCCCGTT,1553,7.348588,10109.0,9.221280,70.907112,75.922445,81.491740,89.069146,0.016124,10109.0,0.073796,False,h01A_P,P,0,Patient01,R,0,Y,Base,Patient01_Base,TNBC,nan,1.327492,15.696615,12,Bcell,16,06,NaN,NaN,Bcell_06
h01A_P_AAACCTGAGGTTACCT,852,6.748760,1890.0,7.544861,36.296296,49.629630,62.962963,81.375661,0.033862,1890.0,0.323280,False,h01A_P,P,0,Patient01,R,0,Y,Base,Patient01_Base,TNBC,CAMRQAGTALIF_CSARPSRQSDNEQFF,-9.247342,-2.434366,27,Tcell,1,NaN,00,NaN,Tcell_00

In [10]:
pd.crosstab(adata_cd45p.obs['batch'], adata_cd45p.obs['pCR'])

pCR        NR      R
batch
h01A_P      0   8270
h01C_P      0  10799
h02A_P      0   7338
h02B_P      0   7603
h02C_P      0   3422
h03A1_P     0   1260
h03A2_P     0   1873
h03B1_P     0   1569
h03B2_P     0   3358
h03C1_P     0     26
h03C2_P     0   1524
h04A_P      0   2090
h04B_P      0    897
h04C_P      0   2431
h05A_P      0   5053
h05B_P      0   2788
h05C_P      0   2429
h06A_P   6311      0
h06B_P   1995      0
h06C_P   4057      0
h07A_P      0   2414
h07B_P      0    383
h07C_P      0   3658
h09A_P      0   8099
h09B_P      0   8081
h09C_P      0   5117
h10A_P   4639      0
h10B_P   3983      0
h10C_P   6960      0
h11A_P      0   2565
h11B_P      0   3539
h11C_P      0   2700
h12A_P      0   2883
h12B_P      0   4642
h12C_P      0   9323
h15A_P    484      0
h15B_P   5156      0
h15C_P    587      0
h16A_P      0   3143
h16B_P      0   6430
h16C_P      0   8324
h17A_P   4750      0
h17B_P   2407      0
h17C_P   1511      0
h18A_P      0   7383
h18B_P      0   5167
h18C_P      0   8479
h19A_P      0   1598
h19B_P      0   5802
h19C_P      0   8011
h20A_P      0    826
h20B_P      0   4281
h20C_P      0   3357
h23A_P      0   6416
h23B_P      0    642
h23C_P      0    267
h26A_P   1173      0
h26B_P    790      0
h26C_P   6249      0
h30A_P      0     92
h30B_P      0   5558
h30C_P      0   6828
h39A_P    205      0
h39B_P   3100      0
h39C_P    370      0
h42A_P      0   2064
h42B_P      0   1219
h42C_P      0   1502
h43A_P      0   1410
h43B_P      0   9501
h43C_P      0   1254
h45A_P    799      0
h45B_P   2746      0
h45C_P     82      0
h46A_P      0   2480
h46B_P      0   4077
h46C_P      0   2135
h47A_P      0   2575
h47B_P      0   3217
h47C_P      0   2168
h48A_P      0    720
h48B_P      0    699
h48C_P      0    291
h52A_P   1520      0
h52B_P    863      0
h52C_P    160      0
h53A_P   7436      0
h53B_P   4360      0
h53C_P   2785      0
h56A_P      0   6242
h56B_P      0   6220
h56C_P      0   3574
h57B_P   5163      0
h57C_P   5070      0
h63A_P      0    168
h63B_P      0    278
h63C_P      0   1206
h64A_P     84      0
h64B_P    864      0
h64C_P    107      0
h66A_P      0    297
h66B_P      0   3851
h66C_P      0     97

In [11]:
pd.crosstab(adata_cd45p.obs['cohort'], adata_cd45p.obs['pCR'])

pCR             NR      R
cohort
Patient01        0  19069
Patient02        0  18363
Patient03T1      0   2855
Patient03T2      0   6755
Patient04        0   5418
Patient05        0  10270
Patient06    12363      0
Patient07        0   6455
Patient09        0  21297
Patient10    15582      0
Patient11        0   8804
Patient12        0  16848
Patient15     6227      0
Patient16        0  17897
Patient17     8668      0
Patient18        0  21029
Patient19        0  15411
Patient20        0   8464
Patient23        0   7325
Patient26     8212      0
Patient30        0  12478
Patient39     3675      0
Patient42        0   4785
Patient43        0  12165
Patient45     3627      0
Patient46        0   8692
Patient47        0   7960
Patient48        0   1710
Patient52     2543      0
Patient53    14581      0
Patient56        0  16036
Patient57    10233      0
Patient63        0   1652
Patient64     1055      0
Patient66        0   4245

In [12]:
del adata_cd45p.obsm
del adata_cd45n.obsm

In [13]:
adata_cd45p.obs.to_csv('/bigdata/zlin/Melanoma_meta/data/TNBC_Shiao/obs_cd45p.csv')
adata_cd45n.obs.to_csv('/bigdata/zlin/Melanoma_meta/data/TNBC_Shiao/obs_cd45n.csv')

In [14]:
del adata_cd45p.obs
del adata_cd45n.obs

In [15]:
diopy.output.write_h5(adata_cd45n, file = '/bigdata/zlin/Melanoma_meta/data/TNBC_Shiao/adata_cd45n.h5')
diopy.output.write_h5(adata_cd45p, file = '/bigdata/zlin/Melanoma_meta/data/TNBC_Shiao/adata_cd45p.h5')